services:
  # Camada Analytics: ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: northwind_analytics
    ports:
      - "8123:8123" # HTTP interface
      - "9004:9000" # Native interface (Changed from 9000 to avoid conflict with MinIO)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=northwind
      - CLICKHOUSE_PASSWORD=northwind
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Camada Frontend: Streamlit Dashboard
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: northwind_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=northwind
      - CLICKHOUSE_PASSWORD=northwind
    command: streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    depends_on:
      clickhouse:
        condition: service_healthy

  # Camada Worker: Ingestor (Python ETL)
  ingestor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: northwind_ingestor
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=northwind
      - CLICKHOUSE_PASSWORD=northwind
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-northwind}
      - S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: tail -f /dev/null # Mantém o container vivo para execuções manuais ou agendadas via Airflow/Cron
    depends_on:
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy

  # Camada Object Storage: MinIO (S3 compatível)
  minio:
    image: minio/minio:latest
    container_name: northwind_minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  clickhouse_data:
  minio_data:
